version:"3.9"
services:
  blackbox-exporter:
   image: prom/blackbox-exporter:v0.22.0
   ports:
    - "9115:9115"
      # dns: 8.8.8.8
   restart: always
   #depends_on:
    #- prometheus
   volumes:
    - ./blackbox:/config"
   command: --config.file=/config/blackbox-exporter.yml      
